Deploy to production

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -297,34 +297,35 @@ stages:
               testResultsFormat: "NUnit"
               testResultsFiles: "$(Pipeline.Workspace)/owaspzap/report.html"
 
-  # - stage: "DeployingToProdEnvironment"
-  #   dependsOn: BuildingJavaCodeWithMavenCopyToJFrog
-  #   condition: and(succeeded('BuildingJavaCodeWithMavenCopyToJFrog'), eq(variables.isProd, true))
-  #   pool:
-  #     name: LinuxAgentPool
-  #   displayName: "Deploying To AWS Prod Environment"
-  #   jobs:
-  #     - deployment: "DeployJARtoProdServer"
-  #       environment:
-  #         name: PROD
-  #         resourceType: VirtualMachine
-  #       strategy:
-  #         runOnce:
-  #           deploy:
-  #             steps:
-  #               - script: |
-  #                   PROC=$(ps -ef | grep -i jar | grep -v grep | awk '{print $2}')
-  #                   if [ -n "$PROC" ]; then
-  #                     echo "Stopping process with PID: $PROC"
-  #                     sudo kill -9 $PROC || echo "Failed to stop process."
-  #                   else
-  #                     echo "No JAR process found. Nothing to stop."
-  #                   fi
-  #                 displayName: "Stop Existing JAR File"
-  #                 continueOnError: true
+  - stage: "DeployingToProdEnvironment"
+    dependsOn: BuildAndPushToAzureArtifacts
+    condition: or(eq(variables.isProd, true), eq(variables.isDev, true)),
+    #condition: and(succeeded('BuildingJavaCodeWithMavenCopyToJFrog'), eq(variables.isProd, true))
+    pool:
+      name: LinuxAgentPool
+    displayName: "Deploying To AWS Prod Environment"
+    jobs:
+      - deployment: "DeployJARtoProdServer"
+        environment:
+          name: PROD
+          resourceType: VirtualMachine
+        strategy:
+          runOnce:
+            deploy:
+              steps:
+                - script: |
+                    PROC=$(ps -ef | grep -i jar | grep -v grep | awk '{print $2}')
+                    if [ -n "$PROC" ]; then
+                      echo "Stopping process with PID: $PROC"
+                      sudo kill -9 $PROC || echo "Failed to stop process."
+                    else
+                      echo "No JAR process found. Nothing to stop."
+                    fi
+                  displayName: "Stop Existing JAR File"
+                  continueOnError: true
 
-  #               - script: |
-  #                   sudo java -jar /home/ubuntu/azagent/_work/1/ROOT$(Build.BuildId).jar/ROOT$(Build.BuildId).jar > /dev/null 2>&1 &
-  #                   echo "Application started successfully."
-  #                 displayName: "Running The Jar File"
-  #                 continueOnError: true
+                - script: |
+                    sudo java -jar /home/ubuntu/azagent/_work/1/ROOT$(Build.BuildId).jar/ROOT$(Build.BuildId).jar > /dev/null 2>&1 &
+                    echo "Application started successfully."
+                  displayName: "Running The Jar File"
+                  continueOnError: true
