add Azure ACI intgeration

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -252,3 +252,88 @@ stages:
               #inlineScript: az group list
             displayName: "Deploy Docker Image to Azure Container Instances"
             continueOnError: true
+  - stage: "DeployingToStagingEnvironment"
+    dependsOn: BuildingJavaCodeWithMavenCopyToJFrog
+    condition: and(succeeded(), eq(variables.isDev, true))
+    pool:
+      name: LinuxAgentPool
+    displayName: "Deploying To AWS Staging Environment"
+    jobs:
+      - deployment: "DeployJARtoStagingServer"
+        environment:
+          name: STAGING
+          resourceType: VirtualMachine
+        strategy:
+          runOnce:
+            deploy:
+              steps:
+                - script: |
+                    PROC=$(ps -ef | grep -i jar | grep -v grep | awk '{print $2}')
+                    if [ -n "$PROC" ]; then
+                      echo "Stopping process with PID: $PROC"
+                      sudo kill -9 $PROC || echo "Failed to stop process."
+                    else
+                      echo "No JAR process found. Nothing to stop."
+                    fi
+                    exit 0  # Force success status
+                  displayName: "Stop Existing JAR File"
+
+                - script: |
+                    sudo java -jar /home/ubuntu/azagent/_work/1/ROOT$(Build.BuildId).jar/ROOT$(Build.BuildId).jar &
+                    echo "Application started successfully."
+                    exit 0  # Force success status
+                  displayName: "Running The Jar File"
+
+  - stage: ZAPOWASPTestingStagingEnvironment
+    condition: and(succeeded(), eq(variables.isDev, true))
+    jobs:
+      - job: ZapTestingStaging
+        timeoutInMinutes: 20
+        steps:
+          - checkout: none
+
+          # Pull the OWASP ZAP image and run the baseline scan
+          - script: |
+              docker pull ghcr.io/zaproxy/zaproxy:stable
+              docker run -u 0 -v $(Pipeline.Workspace)/owaspzap:/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://staging.cloudvishwakarma.in:8080/ -J report.json -r report.html -I -i
+            displayName: "DAST Staging Environment"
+            continueOnError: true
+
+          # Publish the ZAP test results
+          - task: PublishTestResults@2
+            displayName: "Publish Test Results For ZAP Testing"
+            inputs:
+              testResultsFormat: "NUnit"
+              testResultsFiles: "$(Pipeline.Workspace)/owaspzap/report.html"
+
+  # - stage: "DeployingToProdEnvironment"
+  #   dependsOn: BuildingJavaCodeWithMavenCopyToJFrog
+  #   condition: and(succeeded('BuildingJavaCodeWithMavenCopyToJFrog'), eq(variables.isProd, true))
+  #   pool:
+  #     name: LinuxAgentPool
+  #   displayName: "Deploying To AWS Prod Environment"
+  #   jobs:
+  #     - deployment: "DeployJARtoProdServer"
+  #       environment:
+  #         name: PROD
+  #         resourceType: VirtualMachine
+  #       strategy:
+  #         runOnce:
+  #           deploy:
+  #             steps:
+  #               - script: |
+  #                   PROC=$(ps -ef | grep -i jar | grep -v grep | awk '{print $2}')
+  #                   if [ -n "$PROC" ]; then
+  #                     echo "Stopping process with PID: $PROC"
+  #                     sudo kill -9 $PROC || echo "Failed to stop process."
+  #                   else
+  #                     echo "No JAR process found. Nothing to stop."
+  #                   fi
+  #                 displayName: "Stop Existing JAR File"
+  #                 continueOnError: true
+
+  #               - script: |
+  #                   sudo java -jar /home/ubuntu/azagent/_work/1/ROOT$(Build.BuildId).jar/ROOT$(Build.BuildId).jar > /dev/null 2>&1 &
+  #                   echo "Application started successfully."
+  #                 displayName: "Running The Jar File"
+  #                 continueOnError: true
